from __future__ import annotations

import argparse
from collections import Counter
from pathlib import Path
from typing import Optional


def iter_silver_files(silver_root: Path, source_feed: str, dt: str, hour: Optional[str]) -> list[Path]:
    base = silver_root / "trip_updates" / f"feed={source_feed}" / f"dt={dt}"
    rel = f"hour={hour}/*.parquet" if hour else "hour=*/*.parquet"
    return sorted(base.glob(rel))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--silver-root", default="silver")
    ap.add_argument("--source-feed", default="nyct%2Fgtfs")
    ap.add_argument("--dt", required=True, help="YYYY-MM-DD")
    ap.add_argument("--hour", help="HH (00-23). If omitted, scans all hours for dt.")
    ap.add_argument("--route", action="append", default=[], help="route_id filter (repeatable), e.g. --route 6")
    ap.add_argument("--include-all-routes", action="store_true", help="ignore --route filters")
    ap.add_argument("--suffix", help="only include stop_ids ending with this suffix (e.g. S for southbound)")
    ap.add_argument("--top", type=int, default=50, help="how many stop_ids to print")
    ap.add_argument(
        "--min-presence-frac",
        type=float,
        default=0.0,
        help="only include stop_ids present in >= this fraction of snapshots (0..1)",
    )
    ap.add_argument("--write", help="write selected stop_ids (after filters) to this file")
    args = ap.parse_args()

    import pyarrow as pa
    import pyarrow.compute as pc
    import pyarrow.parquet as pq

    silver_root = Path(args.silver_root)
    files = iter_silver_files(silver_root, args.source_feed, args.dt, args.hour)
    if not files:
        raise SystemExit(f"No silver files found under {silver_root}/trip_updates/feed={args.source_feed}/dt={args.dt}")

    route_filter = None
    if not args.include_all_routes and args.route:
        route_filter = set(args.route)

    presence = Counter()  # stop_id -> #snapshots where it appears
    rows = Counter()      # stop_id -> total row count

    snapshots_seen = 0

    for f in files:
        t = pq.read_table(f, columns=["route_id", "stop_id", "eta"])
        # require stop_id and eta (same logic you use elsewhere)
        mask = pc.and_(pc.is_valid(t["stop_id"]), pc.is_valid(t["eta"]))
        t = t.filter(mask)

        if route_filter:
            t = t.filter(pc.is_in(t["route_id"], value_set=pa.array(list(route_filter))))

        # Pull stop_ids
        stop_ids = [s for s in t["stop_id"].to_pylist() if s]
        if args.suffix:
            stop_ids = [s for s in stop_ids if s.endswith(args.suffix)]

        if not stop_ids:
            continue

        snapshots_seen += 1
        rows.update(stop_ids)
        presence.update(set(stop_ids))  # presence is per-snapshot

    if snapshots_seen == 0:
        raise SystemExit("No snapshots had any rows after filters (route/suffix).")

    # Apply presence fraction threshold
    min_presence = int(args.min_presence_frac * snapshots_seen + 1e-9)
    candidates = []
    for stop_id, pres in presence.items():
        if pres >= min_presence:
            candidates.append((stop_id, pres, rows[stop_id]))

    # Sort: most consistently present first, then most rows
    candidates.sort(key=lambda x: (x[1], x[2]), reverse=True)

    print(f"Silver parts scanned: {len(files)}")
    print(f"Snapshots with data after filters: {snapshots_seen}")
    if route_filter:
        print(f"Route filter: {sorted(route_filter)}")
    if args.suffix:
        print(f"Stop suffix filter: {args.suffix!r}")
    if args.min_presence_frac > 0:
        print(f"Min presence: {min_presence}/{snapshots_seen} snapshots (>= {args.min_presence_frac:.2f})")
    print("")
    print(f"{'stop_id':<12} {'presence':>9} {'rows':>9}")
    print("-" * 34)

    top = candidates[: args.top]
    for stop_id, pres, cnt in top:
        print(f"{stop_id:<12} {pres:>9} {cnt:>9}")

    # Write output file if requested
    if args.write:
        out_path = Path(args.write)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        with out_path.open("w", encoding="utf-8") as f:
            f.write("# Generated by scripts/suggest_stop_ids.py\n")
            f.write(f"# dt={args.dt} hour={args.hour or '*'} feed={args.source_feed}\n")
            if route_filter:
                f.write(f"# route={','.join(sorted(route_filter))}\n")
            if args.suffix:
                f.write(f"# stop_id suffix={args.suffix}\n")
            if args.min_presence_frac > 0:
                f.write(f"# min_presence_frac={args.min_presence_frac}\n")
            for stop_id, _, _ in top:
                f.write(f"{stop_id}\n")

        print(f"\nWrote {len(top)} stop_ids to: {out_path}")


if __name__ == "__main__":
    main()
